Lab2/myproject/articleusers/urls.py
from . import  views
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'article'
urlpatterns = [
    url(r'^signup/$', views.signup_view,name = 'signup'),
    url(r'login/$', views.login_view,name='login'),
    url(r'^(?P<userid>\d+)/$', views.get_user_detail),
    url(r'logout/$', views.logout_view, name='logout'),
    url(r'^article$', views.get_article_list, name="list"),
    url(r'^article/create-article/$', views.article_create, name='create'),
    url(r'article/put/(?P<articleid>\d+)/$', views.put_article, name='put'),
    url(r'article/delete/(?P<articleid>\d+)/$',views.delete_article,name='delete'),
]

urlpatterns += staticfiles_urlpatterns()

Lab2/myproject/myproject/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', views.homepage),
    url(r'users/',include('articleusers.urls')),
 #   url(r'articles/', include('articles.urls')),
]

Lab2/myproject/articleusers/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.db.models import TextField
from django.contrib.postgres.fields import ArrayField


class Article(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    author = models.ForeignKey(User, default="None",on_delete='PROTECT')
    checked = models.BooleanField()

    def __str__(self):
        return self.title

class User(models.Model):
    username = models.TextField()
    password: TextField = models.TextField()

    def __str__(self):
        return self.username
#

Lab2/myproject/articleusers/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms import ModelForm

from .models import User,Article

from django.forms import CharField, Form, PasswordInput
from django import forms


class CreateArticle(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'text', 'checked']

class RegisterUserForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'input'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'input'}))
    class Meta:
        model=User
        fields=['username','password1','password2']
        widgets = {
            'username':forms.TextInput(attrs={'class':'input'}),
            'password1': forms.TextInput(attrs={'class': 'input'}),
            'password2': forms.TextInput(attrs={'class': 'input'}),

        }
class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'password1', 'password2']

class LoginUserForm(AuthenticationForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'input'}))
    class Meta:
        model=User
        fields=['username','password']
        widgets = {
            'username':forms.TextInput(attrs={'class':'input'}),
            'password': forms.TextInput(attrs={'class': 'input'}),
        }

Lab2/myproject/articleusers/views.py
from django.contrib import messages
from django.contrib.auth.models import update_last_login
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.template.context_processors import csrf
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from pip._vendor.packaging.requirements import URL

from .models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate, user_logged_in
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .models import Article
from .forms import CreateArticle, RegisterUserForm, LoginUserForm, CreateUserForm


def get_article_list(request):
    articles = Article.objects.all().order_by('title')
    return render(request, 'articleusers/articles_list.html', {'articles': articles})


@login_required(login_url='/users/login')
def put_article(request, articleid):
    if request.method == 'POST':
        form = CreateArticle(request.POST)
        if form.is_valid():
            article = get_object_or_404(Article.objects.all(), author=request.user, pk=int(articleid))
            article.title = form.cleaned_data ['title']
            article.text = form.cleaned_data ['text']
            article.save()
            return redirect('article:list')
    else:
        form = CreateArticle()
    return render(request, 'articleusers/article_update.html', {'form': form})


@login_required(login_url='/users/login')
def delete_article(request, articleid):
    article = get_object_or_404(Article.objects.all(), author=request.user, pk=int(articleid))
    article.delete()
    return redirect('article:list')


@login_required(login_url='/users/login')
def article_create(request):
    if request.method == 'POST':
        form = CreateArticle(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('article:list')
    else:
        form = CreateArticle()
    return render(request, 'articleusers/article_create.html', {'form': form})


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        x = User()
        parsed = json.loads(request.body)
        x.username = parsed['username']
        x.password = parsed['password1']
        x.save()
        return HttpResponse(request.body,status=200)
    else:
        form = UserCreationForm()
    return render(request, 'articleusers/signup.html', {'form': form})



def login_view(request):
    if request.method == 'POST':
        form = LoginUserForm(data=request.POST)
        parsed = json.loads(request.body)
        username = parsed['username']
        password = parsed['password']
        user = authenticate(
            request= request,user=username,password=password
        )
        if user is not None :
            if user.is_active():
                login(request,user)
                return HttpResponseRedirect("/")
        else:
            return HttpResponse(request.body, status=200)
        #if form.is_valid():
#            user = form.get_user()
 #           login(request, user)
    else:
        form = LoginUserForm()
    return render(request, 'articleusers/login.html', {'form': form})


def get_user_detail(request, userid):
    return render(request, 'articleusers/user_detail.html',
                  {'user': User.objects.all() [int(userid) - 1], 'articles': Article.objects.all()})


def logout_view(request):
    logout(request)
    return redirect('http://127.0.0.1:8000/users/login/')

Lab2/myproject/myproject/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

Lab2/myproject/articleusers/templates/articleusers/article_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create article</title>
</head>
<body>
    <div class = "create_article">
            <h2>Create Article</h2>
            <form class = "site-form" action = "{% url 'article:create' %}" method = "post">
                {% csrf_token %}
                {{form.as_p}}
                <input type = "submit" value = "Створити статтю">
            </form>
    </div>
</body>
</html>

Lab2/myproject/articleusers/templates/articleusers/article_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create article</title>
</head>
<body>
    <div class = "put">
    <h2>Update Article</h2>
        <form class = "site-form" action = "" method = "post">
            {% csrf_token %}
            {{form.as_p}}
            <input type = "submit" value = "Створити статтю">
        </form>
    </div>
</body>
</html>

Lab2/myproject/articleusers/templates/articleusers/articles_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article List</title>
    <link rel = "stylesheet" type="text/css" href="{% static 'css/article_list.css'%}">
</head>
<body>
    <h1>Article List:</h1>
    <div class="articles">
        {% csrf_token %}
        {% for article in articles %}
            <div class = "article">
                {% if article.checked %}
                <p>{{article.id}}</p>
                <h2><a href = "#">{{article.title}}</a></h2>
                <p>{{article.text}}</p>
                <p>{{article.author}}</p>
                {% endif %}
            </div>
        {% endfor %}
    </div>
</body>
</html>

Lab2/myproject/articleusers/templates/articleusers/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <script src="{% static 'js/navbar-burger.js' %}"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/basor.css' %}">

</head>
<body>
<nav class="navbar">
    <div class="navbar-brand">

        <div class="navbar-burger burger" data-target="nav-data">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
        <div class="navbar-menu" id="nav-data">
            <a href="/" class="navbar-item">Home</a>
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="field is-grouped">
                        <p class="control">
                            <a href="{% url 'register' %}" class="button is-primary">
                                <span class="button">SIGN UP</span>
                            </a>
                        </p>
                    </div>
                </div>
        </div>
    </div>

</nav>
{% block heading %}  {% endblock %}

{%  block content %}

{%  endblock %}
</body>
</html>

Lab2/myproject/articleusers/templates/articleusers/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}

{% block content %}

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="container">

    <div class="myclass1">
        <img src="../static/css/images/935_oooo.plus.png" class="">

        <div class="content">
            <h2>Login</h2>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <div class="field">
                <input class="form__input" id="username" placeholder=" " {{ form.username }} {% for field in form%}
                    {% if field.html_name == 'username' %} <label for="{{ field.id_for_label }}"
                    class="label">{{ field.html_name }}</label>
                    {% endif %}
                    {% endfor %}
            </div>
            <div class="field">
                <input class="form__input" id="password1" placeholder=" " {{ form.password }} {% for field in form%}
                    {% if field.html_name == 'password' %} <label for="{{ field.id_for_label }}"
                    class="label">{{ field.html_name }}</label>
                    {% endif %}
                    {% endfor %}

            </div>
            <input type="button" value="Log in" class="button is-primary" onclick="loginFunction()">

        </form>
    </div>


</div>
<style>
    .form__input {
        width: 100%;
        padding: 0 0 3px 0;
        border: none;
        border-bottom: 1px solid #e0e0e0;
        background-color: transparent;
        outline: none;
        transition: 0.3s;
        color: #ffffff;
    }
</style>
{% endblock %}
<script>
    function loginFunction() {
        var csrftoken = '{{ csrf_token }}';
        var xhttp;
        xhttp = new XMLHttpRequest();

        var data = JSON.stringify({
            username: document.getElementById("username").value,
            password: document.getElementById("password1").value
        });
        xhttp.onreadystatechange = function () {
            if (this.readyState == 4 && this.status == 200) {
                alert("Welcome, " + document.getElementById("password1").value);
                var json = JSON.parse(responseText);
                console.log(json.username)
                console.log(json.password)
            }
        }
        xhttp.open("POST", "http://127.0.0.1:8000/users/login/");
        xhttp.setRequestHeader("X-CSRFToken", csrftoken);
        xhttp.setRequestHeader("Content-Type", "application/json");
        xhttp.send(data);
    }
</script>

Lab2/myproject/articleusers/templates/articleusers/signup.html
{% extends 'base.html' %}

{% block title %}
Register
{% endblock %}

{% block content %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="container">
    <div class="myclass1">
        <img src="../static/css/images/935_oooo.plus.png" class="">
        <div class="content">
            <h2>Register</h2>
        </div>
        <form method="POST" action="">
            {% csrf_token %}
            {% for non_field_error in form.non_field_errors %}
            <p class="help is-danger">{{ non_field_error }}</p>
            {% endfor %}
            <div class="field">
                <input class="form__input1" id="username" placeholder=" " {{ form.username }} {% for field in form%}
                    {% if field.html_name == 'username' %} <label for="{{ field.id_for_label }}"
                    class="label">{{ field.html_name }}</label>
                {% endif %}
                {% endfor %}
            </div>
            <div class="field">
                <input class="form__input2" id="password1" placeholder=" " {{ form.password1 }} {% for field in form%}
                    {% if field.html_name == 'password1' %} <label for="{{ field.id_for_label }}"
                    class="label">{{ field.html_name }}</label>
                {% endif %}
                {% endfor %}
            </div>
            <div class="field">
                <input class="form__input3" id="password2" placeholder=" " {{ form.password2 }} {% for field in form%}
                    {% if field.html_name == 'password2' %} <label for="{{ field.id_for_label }}"
                    class="label">{{ field.html_name }}</label>
                {% endif %}
                {% endfor %}
            </div>
            <input type="button" value="SIGN UP" class="button is-primary" onclick="signupFunction()">
        </form>
    </div>
</div>
</body>
<style>
    .container{
    display:flex;
    justify-content:center;
    align-items:center;
    height:100vh;
    background-size:120%;
    width:1250px;
    height:550px;
}
</style>
{% endblock %}

Lab2/myproject/articleusers/templates/articleusers/user_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User</title>
</head>
<body>
    <h2>Info about user</h2>
        <div class="user">
            <p><a href = "#">{{user.username}}</a></p>
            <p>Articles of this user : </p>
            {% for article in articles %}
                {% if article.author.id == user.id %}
                <p>{{ article.title }}</p>
                {% endif %}
            {% endfor %}
        </div>
</body>
</html>

Lab2/myproject/articleusers/templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/basor.css' %}">
    <title>{% block title %}

    {% endblock %}</title>

</head>
<body class="body">
{% block content %}

{% endblock %}
<style>
  .container{
  display:flex;
  justify-content:center;
  align-items:center;
  height:100vh;
  background-size:120%;
  width:1250px;
  height:550px;
}
</style>
<script type="text/javascript">
  function signupFunction()
  {
    var csrftoken ='{{ csrf_token }}';
    var xhttp;
    xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function(){
      if(this.readyState == 4 && this.status == 200)
      {
        var json = JSON.parse(this.responseText);
        alert(this.responseText);
      }
    }
    xhttp.open("POST","http://127.0.0.1:8000/users/signup/");
    xhttp.setRequestHeader("X-CSRFToken",csrftoken);
    xhttp.setRequestHeader("Content-Type", "application/json;charset:utf-8");
    var data = JSON.stringify({username : document.getElementById("username").value,
                               password1 : document.getElementById("password1").value,
                               password2 : document.getElementById("password2").value})
    
    xhttp.send(data);
  }

  function loginFunction() {
        var csrftoken = '{{ csrf_token }}';
        var xhttp;
        xhttp = new XMLHttpRequest();

        var data = JSON.stringify({
            username: document.getElementById("username").value,
            password: document.getElementById("password1").value
        });
        xhttp.onreadystatechange = function () {
            if (this.readyState == 4 && this.status == 200) {
                alert("Welcome, " + document.getElementById("username").value);
                var json = JSON.parse(this.responseText);
                console.log(json.username)
                console.log(json.password)
            }
        }
        xhttp.open("POST", "http://127.0.0.1:8000/users/login/");
        xhttp.setRequestHeader("X-CSRFToken", csrftoken);
        xhttp.setRequestHeader("Content-Type", "application/json");
        xhttp.send(data);
    }
</script>
</body>

</html>

Lab2/myproject/articleusers/templates/homepage.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content="width=device-width,initial-scale = 1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../static/css/styler.css">
    <script src="https://kit.fontawesome.com/8e02cd729c.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700|Sintony&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="static/css/fontawesome.min.css">
</head>
<body>
    <header id="header" class = "header">
        <div class="main-header">
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light ">
                    <a class="navbar-brand" href="#">ARTICLE WORLD</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item"><a class="nav-link" href="#article_review">Articles</a></li>
                            <li class="nav-item"><a class="nav-link" href="#searcher">Users</a></li>
                            <li class="nav-item"><a class="nav-link" href="#Contacts_review">Contacts</a></li>
                            <li class="nav-item"><a class="nav-link" href="users/login">Login</a></li>
                            <li class="nav-item"><a class="nav-link" href="users/signup">Register</a></li>
                    </ul>
                </div>
            </nav>
            </div>
        </div>
        <div class="container slider">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="../articleusers/static/css/images/minimo_05.jpg" alt="First slide">
                    </div>
                </div>

            </div>
        </div>
    </header>

    <section id="article_review" class = "article_review">
        <div class="grid-posts">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card">
                            <img class="card-img-top" src="../articleusers/static/css/images/article_01_03.jpg" alt="Card image cap">
                            <div class="card-body">
                                <h3 class="card-title">More than just a music festival</h3>
                                <p class="card-text"> Lorem ipsum dolor sit amet,ei ius persequeris vituperatoribus, ei pro agam dicta inani. Ex eam dictas audiam convenire, eam cibo disputando in. Dolores eleifend pri ei, vis suavitate omittantur definitiones ea. Idque fabellas mel no. Est regione persius dissentias an.
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card">
                            <img class="card-img-top" src="../articleusers/static/css/images/article_02_05.jpg" alt="Card image cap">
                            <div class="card-body">
                                <h3 class="card-title">More than just a music festival</h3>
                                <p class="card-text"> Lorem ipsum dolor sit amet,ei ius persequeris vituperatoribus, ei pro agam dicta inani. Ex eam dictas audiam convenire, eam cibo disputando in. Dolores eleifend pri ei, vis suavitate omittantur definitiones ea. Idque fabellas mel no. Est regione persius dissentias an.
                            </div>
                        </div>
                    </div>
                <div class="load_more_button">
                    <a  href="#" class="article__button" >
                            Load More
                    </a>
                </div>
            </div>
        </div>
        </div>
    </section>
    <section id = "user" class="user">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="btn-group d-flex justify-content-center">
                        <button class="Get">Get User</button>
                        <button class="Delete">Delete User</button>
                        <button class="Put">Put User</button>
                    </div>
                    <div class="search-box d-flex justify-content-center">
                        <input class="search-txt " type="text" name="" placeholder="Type User Id">
                    </div>
                </div>
            </div>
        </div>
    </section>

    <footer id="Contacts_review" class="footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<ul class="socials d-flex justify-content-center">
						<li class="socials__item socials__item_fb">
							<a href="#"></a>
						</li>
						<li class="socials__item socials__item_tw">
							<a href="#"></a>
						</li>
						<li class="socials__item socials__item_g">
							<a href="#"></a>
						</li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
					<div class="line"></div>
				</div>
				<div class="col-lg-4">
					<div class="credits">
						2018 ©   All rights reserved
					</div>
				</div>
				<div class="col-lg-4">
					<div class="line"></div>
				</div>
			</div>
		</div>
	</footer>
</body>
</html>